FROM node:20-alpine

WORKDIR /app

# Install FFmpeg for audio processing
RUN apk add --no-cache ffmpeg openssl

COPY package*.json ./
RUN npm install

COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

CMD ["npm", "run", "worker"]
